name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    name: Lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: "24"
          elixir-version: "1.12"

      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix test
